spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/my_notes
    username: root
    password: bach2612
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: bach2612
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  signerKey: "b/xo9SjUrYj8ewuy9cybMB1Rrw+MkNwuZkYIwr6/sK4FltjjPdxzZlYAMD40UPsD"